---
branches:
  only:
    - master
build: false
build_script:
  - "npm run package-win"
cache:
  - '%APPDATA%\npm-cache'
clone_depth: 1
environment:
  NODE_GYP_DIR: '%USERPROFILE%\.node-gyp'
  ELECTRON_RUN_AS_NODE: 1
  matrix:
    - nodejs_version: 8
image: "Visual Studio 2015"
init:
  - "git config --global core.autocrlf input"
install:
  - ps: "Install-Product node $env:nodejs_version"
  - "npm install --global --production windows-build-tools"
  - "yarn install"
  - "yarn run package-win"
matrix:
  fast_finish: true
platform:
  - x86
shallow_clone: true
test: false
version: "{build}"
